theme: jekyll-theme-cayman
title: Raising the Volume!
description: Amplifying <i>The Soul of Reason</i>
email: soulofreason [at] nyu [dot] edu
menu:
  - label: About <i>The Soul of Reason</i>
    anchor: '#about-the-soul-of-reason-collection'
  - label: About the Project
    anchor: '#about-the-project'
  - label: Contact
    anchor: '#contact'
  - label: Transcribe-a-thon Events
    link: '/virtual-transcription-events'
  - label: Progress
    link: '/progress'
